export declare const COVERAGE_URL: string
export declare const LOCALHOST_URL: string
export declare const ROPSTEN_URL: string
export declare const ROPSTEN_MNEMONIC: string
export declare const KOVAN_URL: string
export declare const KOVAN_MNEMONIC: string
export declare const RINKEBY_URL: string
export declare const RINKEBY_MNEMONIC: string
export declare const HOMESTEAD_URL: string
export declare const HOMESTEAD_MNEMONIC: string
export declare const SOKOL_URL: string
export declare const SOKOL_MNEMONIC: string
export declare const XDAI_URL: string
export declare const XDAI_MNEMONIC: string
export declare const GAS: number
export declare const GAS_PRICE: number
export declare const ARTIFACTS_DIR: string
export declare const ROOT_DIR: string
export declare const SRC_DIR: string
export declare const SRC_DIR_NAME: string
export declare const LEGACY_SRC_DIR: string
export declare const ETHERSCAN_API_KEY: string
